[package]
name = "druid"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Raph Levien <raph.levien@gmail.com>"]
description = "Data-oriented Rust UI design toolkit."

[dependencies]
directwrite = "0.1.2"
direct2d = "0.2.0"

# this is only included for VK_ constants, maybe remove
winapi = "0.3.6"

[dependencies.druid-win-shell]
path = "druid-win-shell"
